# Generated by Django 5.2.3 on 2025-06-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_user_firstname_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='number',
            new_name='count',
        ),
    ]
