# Generated by Django 5.2.3 on 2025-06-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_number_storage_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='author_first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastname',
            new_name='author_last_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='patronymic',
            new_name='author_patronymic',
        ),
    ]
