# Generated by Django 5.2.3 on 2025-06-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
