# Generated by Django 5.2.3 on 2025-06-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_storage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.storage'),
        ),
    ]
