# Generated by Django 5.2.3 on 2025-06-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_book_storage_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_storage',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.storage'),
        ),
    ]
